/**
 * CleverHub - Voice Webhook Edge Function
 *
 * Receives voice session results from the voice pipeline, validates the JWT,
 * stores the encrypted transcript, creates an audit log entry, and broadcasts
 * to the tenant's voice_log Realtime channel.
 *
 * Endpoint: POST /functions/v1/voice-webhook
 *
 * Security:
 *   - Requires valid JWT with tenant_id claim
 *   - Transcript is stored encrypted (pipeline encrypts before sending)
 *   - No raw audio is ever stored
 */

import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type {
  TenantId,
  UserId,
  VoiceSessionId,
  VoiceTier,
  ParsedIntent,
  StageTimestamp,
  AuditAction,
  ApiResult,
} from "@clever/shared";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface VoiceWebhookPayload {
  /** Voice session ID if updating an existing session */
  session_id?: string;
  /** User who triggered the voice session */
  user_id: string;
  /** Device that captured the voice input */
  device_id: string;
  /** Which tier processed this command */
  tier: VoiceTier;
  /** Encrypted transcript (never plaintext over the wire) */
  transcript_encrypted: string;
  /** Parsed intent from the voice pipeline */
  parsed_intent: ParsedIntent | null;
  /** Text response generated by the system */
  response_text: string;
  /** Pipeline stage timestamps for latency tracking */
  stages: StageTimestamp[];
  /** Total end-to-end latency in milliseconds */
  total_latency_ms: number;
  /** Confidence score (0.0 - 1.0) */
  confidence: number;
  /** Processing status */
  status: "processing" | "completed" | "failed" | "confirmation_required";
}

// ---------------------------------------------------------------------------
// Edge Function handler
// ---------------------------------------------------------------------------

Deno.serve(async (req: Request): Promise<Response> => {
  // Only accept POST requests
  if (req.method !== "POST") {
    return new Response(
      JSON.stringify({ data: null, error: { code: "METHOD_NOT_ALLOWED", message: "Only POST is accepted" } }),
      { status: 405, headers: { "Content-Type": "application/json" } }
    );
  }

  try {
    // -----------------------------------------------------------------------
    // 1. Extract and validate JWT
    // -----------------------------------------------------------------------
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return jsonError("UNAUTHORIZED", "Missing or invalid Authorization header", 401);
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY");

    if (!supabaseUrl || !supabaseServiceKey || !supabaseAnonKey) {
      return jsonError("SERVER_ERROR", "Missing Supabase environment configuration", 500);
    }

    // Create a client using the user's JWT for RLS-scoped operations
    const userToken = authHeader.replace("Bearer ", "");
    const userClient = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: `Bearer ${userToken}` } },
    });

    // Verify the token and extract claims
    const { data: { user }, error: authError } = await userClient.auth.getUser(userToken);
    if (authError || !user) {
      return jsonError("UNAUTHORIZED", "Invalid or expired JWT", 401);
    }

    // Service client for operations that bypass RLS (audit logging, realtime broadcast)
    const serviceClient = createClient(supabaseUrl, supabaseServiceKey);

    // Extract tenant_id from JWT app_metadata or custom claims
    // The custom_access_token_hook adds these to the JWT
    const { data: { session } } = await userClient.auth.getSession();
    const tenantId = extractTenantId(user, session);

    if (!tenantId) {
      return jsonError("FORBIDDEN", "No tenant_id found in JWT claims", 403);
    }

    // -----------------------------------------------------------------------
    // 2. Parse and validate payload
    // -----------------------------------------------------------------------
    const payload: VoiceWebhookPayload = await req.json();
    const validationError = validatePayload(payload);
    if (validationError) {
      return jsonError("VALIDATION_ERROR", validationError, 400);
    }

    // -----------------------------------------------------------------------
    // 3. Store voice session
    // -----------------------------------------------------------------------
    const sessionResult = await storeVoiceSession(userClient, tenantId, payload);
    if (!sessionResult.success) {
      return jsonError("DB_ERROR", sessionResult.error, 500);
    }

    const sessionId = sessionResult.id;

    // -----------------------------------------------------------------------
    // 4. Store encrypted transcript record
    // -----------------------------------------------------------------------
    const transcriptResult = await storeTranscript(userClient, {
      session_id: sessionId,
      tenant_id: tenantId,
      user_id: payload.user_id,
      transcript_encrypted: payload.transcript_encrypted,
      intent_summary: payload.parsed_intent
        ? `${payload.parsed_intent.domain}.${payload.parsed_intent.action}`
        : "unrecognized",
      tier_used: payload.tier,
      latency_ms: payload.total_latency_ms,
    });

    if (!transcriptResult.success) {
      // Non-fatal: session was stored, log the transcript error
      console.error("Failed to store transcript:", transcriptResult.error);
    }

    // -----------------------------------------------------------------------
    // 5. Create audit log entry
    // -----------------------------------------------------------------------
    await createAuditLog(serviceClient, {
      tenant_id: tenantId,
      user_id: payload.user_id,
      device_id: payload.device_id,
      voice_session_id: sessionId,
      action: "voice_command_processed",
      details: {
        tier: payload.tier,
        confidence: payload.confidence,
        status: payload.status,
        total_latency_ms: payload.total_latency_ms,
        intent: payload.parsed_intent
          ? `${payload.parsed_intent.domain}.${payload.parsed_intent.action}`
          : null,
      },
      ip_address: req.headers.get("x-forwarded-for") ?? req.headers.get("x-real-ip") ?? null,
    });

    // -----------------------------------------------------------------------
    // 6. Broadcast to Realtime channel
    // -----------------------------------------------------------------------
    await broadcastVoiceEvent(serviceClient, tenantId, {
      session_id: sessionId,
      user_id: payload.user_id,
      device_id: payload.device_id,
      tier: payload.tier,
      status: payload.status,
      confidence: payload.confidence,
      intent_summary: payload.parsed_intent
        ? `${payload.parsed_intent.domain}.${payload.parsed_intent.action}`
        : "unrecognized",
      total_latency_ms: payload.total_latency_ms,
      timestamp: new Date().toISOString(),
    });

    // -----------------------------------------------------------------------
    // 7. Return success
    // -----------------------------------------------------------------------
    const response: ApiResult<{ session_id: string }> = {
      data: { session_id: sessionId },
      error: null,
    };

    return new Response(JSON.stringify(response), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (err) {
    console.error("Voice webhook error:", err);
    return jsonError("INTERNAL_ERROR", "An unexpected error occurred", 500);
  }
});

// ---------------------------------------------------------------------------
// Helper Functions
// ---------------------------------------------------------------------------

function extractTenantId(
  user: { id: string; app_metadata?: Record<string, unknown>; user_metadata?: Record<string, unknown> },
  session: { access_token?: string } | null
): string | null {
  // Try app_metadata first (set by custom_access_token_hook)
  if (user.app_metadata?.["tenant_id"]) {
    return user.app_metadata["tenant_id"] as string;
  }
  // Fallback to user_metadata
  if (user.user_metadata?.["tenant_id"]) {
    return user.user_metadata["tenant_id"] as string;
  }
  // If neither, try decoding the JWT directly
  if (session?.access_token) {
    try {
      const parts = session.access_token.split(".");
      if (parts[1]) {
        const payload = JSON.parse(atob(parts[1]));
        if (payload.tenant_id) return payload.tenant_id as string;
      }
    } catch {
      // JWT decode failed, return null
    }
  }
  return null;
}

function validatePayload(payload: VoiceWebhookPayload): string | null {
  if (!payload.user_id) return "user_id is required";
  if (!payload.device_id) return "device_id is required";
  if (!payload.tier) return "tier is required";
  if (!payload.transcript_encrypted) return "transcript_encrypted is required";
  if (typeof payload.confidence !== "number" || payload.confidence < 0 || payload.confidence > 1) {
    return "confidence must be a number between 0 and 1";
  }
  if (typeof payload.total_latency_ms !== "number" || payload.total_latency_ms < 0) {
    return "total_latency_ms must be a non-negative number";
  }
  if (!payload.status) return "status is required";
  const validStatuses = ["processing", "completed", "failed", "confirmation_required"];
  if (!validStatuses.includes(payload.status)) {
    return `status must be one of: ${validStatuses.join(", ")}`;
  }
  return null;
}

async function storeVoiceSession(
  client: SupabaseClient,
  tenantId: string,
  payload: VoiceWebhookPayload
): Promise<{ success: true; id: string } | { success: false; error: string }> {
  if (payload.session_id) {
    // Update existing session
    const { data, error } = await client
      .from("voice_sessions")
      .update({
        status: payload.status,
        parsed_intent: payload.parsed_intent,
        response_text: payload.response_text,
        stages: payload.stages,
        total_latency_ms: payload.total_latency_ms,
        confidence: payload.confidence,
      })
      .eq("id", payload.session_id)
      .eq("tenant_id", tenantId)
      .select("id")
      .single();

    if (error) return { success: false, error: error.message };
    return { success: true, id: data.id as string };
  }

  // Create new session
  const { data, error } = await client
    .from("voice_sessions")
    .insert({
      tenant_id: tenantId,
      user_id: payload.user_id,
      device_id: payload.device_id,
      tier: payload.tier,
      transcript_encrypted: payload.transcript_encrypted,
      parsed_intent: payload.parsed_intent,
      response_text: payload.response_text,
      stages: payload.stages,
      total_latency_ms: payload.total_latency_ms,
      confidence: payload.confidence,
      status: payload.status,
    })
    .select("id")
    .single();

  if (error) return { success: false, error: error.message };
  return { success: true, id: data.id as string };
}

async function storeTranscript(
  client: SupabaseClient,
  record: {
    session_id: string;
    tenant_id: string;
    user_id: string;
    transcript_encrypted: string;
    intent_summary: string;
    tier_used: VoiceTier;
    latency_ms: number;
  }
): Promise<{ success: true } | { success: false; error: string }> {
  const { error } = await client.from("voice_transcripts").insert(record);
  if (error) return { success: false, error: error.message };
  return { success: true };
}

async function createAuditLog(
  client: SupabaseClient,
  entry: {
    tenant_id: string;
    user_id: string;
    device_id: string;
    voice_session_id: string;
    action: AuditAction;
    details: Record<string, unknown>;
    ip_address: string | null;
  }
): Promise<void> {
  const { error } = await client.from("audit_logs").insert(entry);
  if (error) {
    // Audit log failure is non-fatal but must be logged
    console.error("Failed to create audit log:", error.message);
  }
}

async function broadcastVoiceEvent(
  client: SupabaseClient,
  tenantId: string,
  payload: Record<string, unknown>
): Promise<void> {
  const channelName = `voice_log:${tenantId}`;
  const channel = client.channel(channelName);

  await channel.send({
    type: "broadcast",
    event: "voice_session",
    payload,
  });

  // Clean up the channel subscription after broadcast
  await client.removeChannel(channel);
}

function jsonError(code: string, message: string, status: number): Response {
  const body: ApiResult<never> = {
    data: null,
    error: { code, message },
  };
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}
